BiocManager::install("DESeq2")
library("DESeq2")
install.packages("survival")
library("DESeq2")
install.packages("foreign")
library("DESeq2")
files = c("SLE001.counts","SLE002.counts","SLE004.counts","SLE005.counts","SLE006.counts","SLE007.counts","SLE008.counts","SLE010.counts","SLE011.counts","SLE012.counts","SLE013.counts","SLE014.counts","SLE015.counts","SLE016.counts")
cond = c("A","B","B","A","B","A","B","B","B","B","B","A","A","A")
sTable = data.frame(sampleName = files, fileName = files, condition = cond)
dds <-DESeqDataSetFromHTSeqCount(sampleTable=sTable, directory = "D:\\git\\CMU-DEG-Tutorial\\Data", design = ~condition)
dds <- DESeq(dds)
res <- results(dds)
res
plotMA(res, ylim=c(-2,2))
write.csv(as.data.frame(res), file="condition_sle.csv")
